package io.github.primelib.primecodegen.core.domain.template

import io.swagger.v3.oas.models.OpenAPI
import org.apache.commons.lang3.StringUtils

@Suppress("MaxLineLength", "NestedBlockDepth")
data class OpenAPIDetails(
    var appName: String? = null,
    var appVersion: String? = null,
    var appDescription: String? = null,
    var infoEmail: String? = null,
    var infoName: String? = null,
    var infoUrl: String? = null,
    var licenseInfo: String? = null,
    var licenseUrl: String? = null,
    var licenseName: String? = null,
    var termsOfService: String? = null,
    var hasFormParameters: Boolean = false,
) {
    companion object {
        fun of(openAPI: OpenAPI): OpenAPIDetails {
            val details = OpenAPIDetails()

            // info
            openAPI.info?.let { info ->
                details.appName = info.title
                details.appVersion = StringUtils.defaultIfEmpty(info.version, "1.0.0")
                details.appDescription = StringUtils.defaultIfEmpty(info.description, "No description provided (generated by OpenAPI Generator)")
                info.contact?.let { contact ->
                    details.infoEmail = contact.email
                    details.infoName = contact.name
                    details.infoUrl = contact.url
                }
                info.license?.let { license ->
                    details.licenseName = license.name
                    details.licenseInfo = license.name
                    details.licenseUrl = license.url
                }
                details.termsOfService = info.termsOfService
            }

            // has form parameters
            openAPI.paths?.let { paths ->
                paths.forEach { (path, pathItem) ->
                    pathItem.readOperations().forEach { operation ->
                        val hasFormParam = operation.parameters?.any { it.`in` == "formData" } == true ||
                            operation.requestBody?.content?.containsKey("multipart/form-data") == true ||
                            operation.requestBody?.content?.containsKey("application/x-www-form-urlencoded") == true
                        if (hasFormParam) {
                            details.hasFormParameters = true
                        }
                    }
                }
            }

            return details
        }
    }
}
